import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';
import Amplify, {XR} from 'aws-amplify';
import awsconfig from './aws-exports';
import scene1Config from './sumerian_exports_065ddb231a1f4bd38a9130fa0d4a09d5.json'; // This file will be generated by the Sumerian AWS Console
Amplify.configure({
    ...awsconfig,
    XR: { // XR category configuration
        region: 'eu-central-1', // Sumerian region
        scenes: {
            "Forest": { // Friendly scene name
                sceneConfig: scene1Config, // Scene configuration from Sumerian publish
                publishParamOverrides: { alpha: true }
            }
        }
    }
});

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
